# Generated by Django 6.0.7 on 2026-07-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=200)),
                ("job_id", models.CharField(max_length=50, unique=True)),
                ("location", models.CharField(max_length=100)),
                ("exp", models.CharField(max_length=100)),
                ("education", models.CharField(max_length=200)),
                ("skills", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
    ]
